# This manifest file contains the configuration for the catalouge application, including a ConfigMap for database configuration, a Deployment for the application, and a Service to expose it.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Values.service.name}}"
  namespace: "{{.Values.deployment.namespace}}"
data:
  MONGO_URL: "mongodb://mongodb-service:27017/catalogue"
  MONGO_DB: "true"
