apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.deploymentName }}"
  namespace: "{{.Values.deployment.namspace}}"
  labels:
    app: "{{.Values.deployment.deployment-name}}"
    project: roboshop
    environment: dev
    purpose: poc

  annotations:
    kubernetes.io/change-cause: "{{.Values.deployment.changecause}}"

    # the namespace in which the deployment will be created 
spec: 
  replicas: {{ .Values.deployment.replicas }}         #integer should be no quoted 
  selector:
    matchLabels:  
      app: "{{ .Values.deployment.deploymentName }}"
      project: roboshop
      environment: dev
      purpose: poc

# the pod template

  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.deploymentName }}"
        project: roboshop
        environment: dev
        purpose: poc
    spec:
      containers:
      - name: "{{.Values.container.name}}"
        image: "{{ .Values.deployment.imageVersion }}"
        ports:
        - containerPort: 27017