#Service 

apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.service.name}}"
  namespace: "{{.Values.deployment.namespace}}"
  labels:
    project: roboshop
    environment: dev
    purpose: poc

spec:
  type: NodePort 
  selector:
    app: "{{ .Values.deployment.deploymentName }}"
    project: roboshop
    environment: dev
    purpose: poc 
  
  ports:
  - protocol: TCP
    port: 8080  #service port
    targetPort: 80 #container port
    nodePort: 30017