deployment:
  replicas: 1
  changecause: "installing the lastest version - added the config to the pod added catalogue "
  imageVersion: sandeep0109/catalogue:2.2.2
  deploymentName: catalougedeployment
  namespace: catalouge

service:
  name: catalogue

container:
  name: catalogue

